#!/usr/bin/env node
// The iOS / iPadOS / watchOS apps' version follows the repository's package.json,
// exactly as the Android app's does (android/app/build.gradle.kts):
//
//   MARKETING_VERSION        = x.y.z                     (CFBundleShortVersionString)
//   CURRENT_PROJECT_VERSION  = x·10000 + y·100 + z       (CFBundleVersion — Android versionCode)
//
// Both go to ios/Config/Version.xcconfig, which ios/Config/Base.xcconfig includes for
// every target of ios/M5cet.xcodeproj (app, notification extension, watch app, tests).
//
//   node ios/scripts/sync-version.mjs           write the file (no change when it is current)
//   node ios/scripts/sync-version.mjs --check   exit 1 when the file is out of date (CI)

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const target = join(here, "..", "Config", "Version.xcconfig");

const version = JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;
const m = /^(\d+)\.(\d+)\.(\d+)/.exec(String(version));
if (!m) {
  console.error(`package.json version "${version}" is not x.y.z`);
  process.exit(2);
}
const [major, minor, patch] = m.slice(1).map(Number);
if (minor > 99 || patch > 99) {
  console.error(`package.json version ${version}: minor and patch must be below 100 (build = x·10000 + y·100 + z)`);
  process.exit(2);
}
const marketing = `${major}.${minor}.${patch}`;
const build = major * 10000 + minor * 100 + patch;

const text = `// Generated by ios/scripts/sync-version.mjs from package.json — do not edit by hand.
// Run \`node ios/scripts/sync-version.mjs\` after a version change (CI checks it).
MARKETING_VERSION = ${marketing}
CURRENT_PROJECT_VERSION = ${build}
`;

const current = existsSync(target) ? readFileSync(target, "utf8") : "";
const name = relative(root, target);
if (process.argv.includes("--check")) {
  if (current !== text) {
    console.error(`${name} is out of date: run node ios/scripts/sync-version.mjs (package.json is ${version})`);
    process.exit(1);
  }
  console.log(`${name}: ${marketing} (${build}) ✓`);
} else if (current === text) {
  console.log(`${name}: ${marketing} (${build}), already current`);
} else {
  writeFileSync(target, text);
  console.log(`${name}: ${marketing} (${build}) written`);
}
