// Test support: the repository's vectors and the fixtures generated by the
// server's own code (fixtures/generate-fixtures.ts), an in-memory hub socket,
// a stub HTTP transport, and test-only implementations of the protocols the
// crypto layer provides in the app (Ed25519 hub proof, ECIES, KT verifier) —
// small CryptoKit versions so the network logic runs against real vectors.

import CryptoKit
import Foundation
import Synchronization
import Testing
@testable import M5Net

/* --------------------------------------------------------------- files */

enum Fixtures {
    /// The repository root (…/ios/M5Kit/Tests/M5NetTests/TestSupport.swift → five levels up).
    static let repo: URL = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()
        .deletingLastPathComponent().deletingLastPathComponent()
    static let here: URL = URL(fileURLWithPath: #filePath).deletingLastPathComponent().appendingPathComponent("fixtures")

    static func json(_ url: URL) throws -> NetJSON { try NetJSON.parse(try Data(contentsOf: url)) }
    static func hubFrames() throws -> NetJSON { try json(here.appendingPathComponent("hub-frames.json")) }
    static func device() throws -> NetJSON { try json(here.appendingPathComponent("device-vectors.json")) }
    static func p4() throws -> NetJSON { try json(repo.appendingPathComponent("test/vectors/p4.json")) }
    static func interop() throws -> NetJSON { try json(repo.appendingPathComponent("test/fixtures/android-interop.json")) }
}

/* ------------------------------------------------------------- waiting */

/// Polls `condition` until it holds (or fails the test after `timeout`).
func eventually(_ what: String, timeout: Duration = .seconds(3), _ condition: @Sendable () async -> Bool) async {
    let deadline = ContinuousClock.now + timeout
    while ContinuousClock.now < deadline {
        if await condition() { return }
        try? await Task.sleep(for: .milliseconds(10))
    }
    Issue.record("timed out waiting for \(what)")
}

/// Collects a connection's events for the test to look at.
actor EventLog {
    private(set) var events: [HubEvent] = []

    static func watch(_ stream: AsyncStream<HubEvent>) -> EventLog {
        let log = EventLog()
        Task { for await e in stream { await log.add(e) } }
        return log
    }

    private func add(_ e: HubEvent) { events.append(e) }

    var statuses: [HubStatus] { events.compactMap { if case .status(let s) = $0 { return s }; return nil } }
    var notices: [HubNotice] { events.compactMap { if case .notice(let n) = $0 { return n }; return nil } }
    var frameTypes: [String] { events.compactMap { if case .frame(let f, _) = $0 { return f.type }; return nil } }
    func count(_ s: HubStatus) -> Int { statuses.filter { $0 == s }.count }
}

/* ------------------------------------------------- an in-memory hub socket */

/// A queue one side fills and the other awaits.
final class Mailbox<T: Sendable>: @unchecked Sendable {
    private struct S {
        var items: [T] = []
        var waiters: [(id: Int, c: CheckedContinuation<T?, Never>)] = []
        var closed = false
        var seq = 0
    }
    private let s = Mutex(S())

    func put(_ item: T) {
        let w: CheckedContinuation<T?, Never>? = s.withLock { st in
            if st.closed { return nil }
            if !st.waiters.isEmpty { return st.waiters.removeFirst().c }
            st.items.append(item)
            return nil
        }
        w?.resume(returning: item)
    }

    func close() {
        let ws = s.withLock { st -> [CheckedContinuation<T?, Never>] in
            st.closed = true
            defer { st.waiters = [] }
            return st.waiters.map(\.c)
        }
        for w in ws { w.resume(returning: nil) }
    }

    /// The next item, nil when closed and empty.
    func take() async -> T? { await take(timeout: nil) }

    /// The next item within `timeout` (nil: no limit), else nil.
    func take(timeout: Duration?) async -> T? {
        await withCheckedContinuation { (c: CheckedContinuation<T?, Never>) in
            let (ready, value, id): (Bool, T?, Int) = s.withLock { st in
                if !st.items.isEmpty { return (true, st.items.removeFirst(), 0) }
                if st.closed { return (true, nil, 0) }
                st.seq += 1
                st.waiters.append((st.seq, c))
                return (false, nil, st.seq)
            }
            if ready { c.resume(returning: value); return }
            guard let timeout else { return }
            Task {
                try? await Task.sleep(for: timeout)
                let w = self.s.withLock { st -> CheckedContinuation<T?, Never>? in
                    guard let i = st.waiters.firstIndex(where: { $0.id == id }) else { return nil }
                    return st.waiters.remove(at: i).c
                }
                w?.resume(returning: nil)
            }
        }
    }

    var pending: [T] { s.withLock { $0.items } }
}

final class MockSocket: HubSocket, @unchecked Sendable {
    /// What the client sent (text frames as JSON).
    let sent = Mailbox<HubMessage>()
    private let inbox = Mailbox<Result<HubMessage, HubSocketClosed>>()
    private let state = Mutex<(closedByClient: Int?, aborted: Bool)>((nil, false))

    var clientCloseCode: Int? { state.withLock { $0.closedByClient } }
    var aborted: Bool { state.withLock { $0.aborted } }

    func send(_ message: HubMessage) async throws {
        if state.withLock({ $0.closedByClient != nil || $0.aborted }) { throw HubSocketClosed(code: 1006, reason: "closed") }
        sent.put(message)
    }

    func receive() async throws -> HubMessage {
        guard let r = await inbox.take() else { throw HubSocketClosed(code: clientCloseCode ?? 1006, reason: "") }
        return try r.get()
    }

    func close(code: Int, reason: String) {
        state.withLock { $0.closedByClient = code }
        inbox.put(.failure(HubSocketClosed(code: code, reason: reason)))
        inbox.close()
    }

    func abort() {
        state.withLock { $0.aborted = true }
        inbox.put(.failure(HubSocketClosed(code: 1006, reason: "aborted")))
        inbox.close()
    }

    /* the server's side */

    func push(_ frame: NetJSON) { inbox.put(.success(.text(frame.text))) }
    func pushRaw(_ text: String) { inbox.put(.success(.text(text))) }
    func pushBinary(_ d: Data) { inbox.put(.success(.binary(d))) }
    func serverClose(_ code: Int, _ reason: String = "") {
        inbox.put(.failure(HubSocketClosed(code: code, reason: reason)))
        inbox.close()
    }

    /// The next text frame the client sent, parsed (nil after `timeout`).
    func next(timeout: Duration = .seconds(2)) async -> NetJSON? {
        guard let m = await sent.take(timeout: timeout), case .text(let t) = m else { return nil }
        return try? NetJSON.parse(t)
    }

    /// The next frame of this type (others are skipped).
    func next(_ type: String, timeout: Duration = .seconds(2)) async -> NetJSON? {
        let deadline = ContinuousClock.now + timeout
        while ContinuousClock.now < deadline {
            guard let f = await next(timeout: deadline - ContinuousClock.now) else { return nil }
            if f.str("type") == type { return f }
        }
        return nil
    }

    /// A hello with a nonce (24 bytes base64url).
    func hello(nonce: String? = Bytes.b64url(Data(repeating: 7, count: 24)), peerId: String = "p-server") {
        var h: NetJSON = ["type": "hello", "protocol": 2, "peerId": .string(peerId), "connId": "c-1", "serverTime": 1, "features": ["bin"]]
        if let nonce { h = h.with("nonce", .string(nonce)) }
        push(h)
    }

    func joined(peerId: String, resume: String = "cmVzdW1lLXNlY3JldC0wMTIzNDU2Nzg5YWJjZGVm", proven: Bool? = true, peers: [NetJSON] = []) {
        var j: NetJSON = ["type": "joined", "protocol": 2, "peerId": .string(peerId), "room": "r", "resume": .string(resume), "peers": .array(peers),
                          "away": [], "held": [], "account": .null]
        if let proven { j = j.with("proven", .bool(proven)) }
        push(j)
    }
}

final class MockHubTransport: HubTransport, @unchecked Sendable {
    let sockets = Mailbox<MockSocket>()
    private let failures = Mutex(0)
    private let opened = Mutex<[URL]>([])

    /// The next `n` connects fail.
    func fail(_ n: Int) { failures.withLock { $0 = n } }
    var urls: [URL] { opened.withLock { $0 } }

    func connect(to url: URL, headers: [String: String], timeout: Duration) async throws -> any HubSocket {
        opened.withLock { $0.append(url) }
        if failures.withLock({ f -> Bool in if f > 0 { f -= 1; return true }; return false }) { throw NetError.network("refused") }
        let s = MockSocket()
        sockets.put(s)
        return s
    }

    /// The next socket the client opened.
    func accept(timeout: Duration = .seconds(2)) async -> MockSocket? { await sockets.take(timeout: timeout) }
}

extension HubTiming {
    /// Short timings for tests.
    static var fast: HubTiming {
        var t = HubTiming()
        t.joinFallback = .milliseconds(200)
        t.heartbeat = .seconds(30)
        t.deadAfter = .seconds(60)
        t.presenceGap = .milliseconds(150)
        t.connectTimeout = .seconds(2)
        t.backoffBaseMs = 10
        t.backoffCapMs = 40
        t.backoffMinMs = 5
        t.answerTimeout = .milliseconds(300)
        return t
    }
}

/* ----------------------------------------------------------- stub HTTP */

final class StubHTTP: HTTPTransport, @unchecked Sendable {
    typealias Handler = @Sendable (HTTPRequest) async throws -> HTTPResponse
    private let handler: Handler
    private let log = Mutex<[HTTPRequest]>([])

    init(_ handler: @escaping Handler) { self.handler = handler }

    var requests: [HTTPRequest] { log.withLock { $0 } }

    func send(_ request: HTTPRequest, progress: HTTPProgress?) async throws -> HTTPResponse {
        log.withLock { $0.append(request) }
        return try await handler(request)
    }

    static func json(_ status: Int = 200, _ body: NetJSON) -> HTTPResponse { HTTPResponse(status: status, headers: ["Content-Type": "application/json"], body: body.data) }
}

extension HTTPRequest {
    var path: String { url.path + (url.query.map { "?\($0)" } ?? "") }
    var jsonBody: NetJSON? { body.flatMap { try? NetJSON.parse($0) } }
}

/* ---------------------------------------------- test crypto (CryptoKit) */

/// The room's hub key from a seed (M5Crypto derives the seed from the room secret).
struct TestHubSigner: HubProofSigner {
    let key: Curve25519.Signing.PrivateKey
    init(seed: Data) throws { key = try Curve25519.Signing.PrivateKey(rawRepresentation: seed) }
    func signHubJoin(_ message: Data) async throws -> (publicKey: Data, signature: Data) {
        (key.publicKey.rawRepresentation, try key.signature(for: message))
    }
}

/// ECIES as crypto.ts eciesOpen does it, with a P-256 key in this process.
struct TestEciesOpener: EciesOpener {
    static let label = "m5cet/android/ecies/1"
    let key: P256.KeyAgreement.PrivateKey
    init(pkcs8Base64: String) throws { key = try P256.KeyAgreement.PrivateKey(derRepresentation: Bytes.unb64(pkcs8Base64)!) }
    func publicKeySPKI() async throws -> String { Bytes.b64(key.publicKey.derRepresentation) }
    func open(_ wire: EciesEnvelope, deviceId: String, purpose: String) async throws -> Data {
        let eph = try P256.KeyAgreement.PublicKey(derRepresentation: Bytes.unb64(wire.e)!)
        let shared = try key.sharedSecretFromKeyAgreement(with: eph)
        let k = shared.hkdfDerivedSymmetricKey(using: SHA256.self, salt: Data(Self.label.utf8), sharedInfo: Data("\(purpose)|\(deviceId)".utf8), outputByteCount: 32)
        let all = Bytes.unb64(wire.ct)!
        let box = try AES.GCM.SealedBox(nonce: AES.GCM.Nonce(data: Bytes.unb64(wire.iv)!), ciphertext: all.dropLast(16), tag: all.suffix(16))
        return try AES.GCM.open(box, using: k, authenticating: Data("\(Self.label)|\(purpose)|\(deviceId)".utf8))
    }
}

/// Key transparency's crypto (Ed25519 tree heads, RFC 6962 / 9162 Merkle proofs) for the tests.
struct TestKtVerifier: KtVerifier {
    func verifySTH(_ sth: NetJSON, key: String) -> Bool {
        guard let size = sth["size"]?.int64Value, size >= 0, let ts = sth["ts"]?.int64Value, ts >= 0, let root = sth["root"]?.stringValue,
              Bytes.unb64(root)?.count == 32, let sig = sth["sig"]?.stringValue.flatMap(Bytes.unb64), sig.count == 64,
              let k = Bytes.unb64(key), let pub = try? Curve25519.Signing.PublicKey(rawRepresentation: k) else { return false }
        return pub.isValidSignature(sig, for: Data("m5cet/kt/sth/4|\(size)|\(root)|\(ts)".utf8))
    }

    static func node(_ l: Data, _ r: Data) -> Data { Bytes.sha256(Data([1]) + l + r) }
    static func leaf(_ text: String) -> Data { Bytes.sha256(Data([0]) + Data(text.utf8)) }

    func verifyConsistency(from first: Int64, to second: Int64, fromRoot: Data, toRoot: Data, proof: [Data]) -> Bool {
        if first == second { return proof.isEmpty && fromRoot == toRoot }
        if first == 0 || first > second || proof.isEmpty { return false }
        var path = proof
        if first & (first - 1) == 0 { path.insert(fromRoot, at: 0) }
        var fn = first - 1, sn = second - 1
        while fn & 1 == 1 { fn >>= 1; sn >>= 1 }
        var fr = path[0], sr = path[0]
        for c in path.dropFirst() {
            if sn == 0 { return false }
            if fn & 1 == 1 || fn == sn {
                fr = Self.node(c, fr)
                sr = Self.node(c, sr)
                if fn & 1 == 0 { while fn & 1 == 0 && fn != 0 { fn >>= 1; sn >>= 1 } }
            } else {
                sr = Self.node(sr, c)
            }
            fn >>= 1; sn >>= 1
        }
        return fr == fromRoot && sr == toRoot && sn == 0
    }

    static func verifyInclusion(leaf: Data, index: Int64, size: Int64, path: [Data], root: Data) -> Bool {
        if index >= size { return false }
        var fn = index, sn = size - 1
        var r = leaf
        for p in path {
            if sn == 0 { return false }
            if fn & 1 == 1 || fn == sn {
                r = node(p, r)
                if fn & 1 == 0 { while fn & 1 == 0 && fn != 0 { fn >>= 1; sn >>= 1 } }
            } else {
                r = node(r, p)
            }
            fn >>= 1; sn >>= 1
        }
        return sn == 0 && r == root
    }

    static func canonical(_ e: NetJSON) -> String? {
        switch e.str("t") {
        case "acct": return "{\"t\":\"acct\",\"u\":\"\(e.str("u"))\",\"apk\":\"\(e.str("apk"))\",\"ts\":\(e.int("ts"))}"
        case "dev": return "{\"t\":\"dev\",\"u\":\"\(e.str("u"))\",\"apk\":\"\(e.str("apk"))\",\"dpk\":\"\(e.str("dpk"))\",\"exp\":\(e.int("exp")),\"ts\":\(e.int("ts"))}"
        case "rev": return "{\"t\":\"rev\",\"u\":\"\(e.str("u"))\",\"apk\":\"\(e.str("apk"))\",\"dpk\":\"\(e.str("dpk"))\",\"ts\":\(e.int("ts"))}"
        default: return nil
        }
    }

    func verifyLookup(_ lookup: NetJSON, key: String, u: String?) -> KtCheckedLookup {
        guard let items = lookup.arr("entries"), let sth = lookup.obj("sth") else { return .no("malformed") }
        guard verifySTH(sth, key: key) else { return .no("bad-signature") }
        let root = Bytes.unb64(sth.str("root"))!
        var out: [KtLogEntry] = []
        for it in items {
            guard let entry = it.obj("entry"), let text = Self.canonical(entry), let index = it["index"]?.int64Value,
                  let path = it.arr("proof")?.compactMap({ $0.stringValue.flatMap(Bytes.unb64) }) else { return .no("malformed") }
            if let u, entry.str("u") != u { return .no("wrong-user") }
            guard Self.verifyInclusion(leaf: Self.leaf(text), index: index, size: sth.int("size"), path: path, root: root) else { return .no("not-included") }
            out.append(KtLogEntry(entry: entry, index: index))
        }
        return KtCheckedLookup(ok: true, why: nil, sth: sth, entries: out)
    }
}

/// Mailbox and certificate checks for the relay tests: a table of what is valid.
struct TestRelayChecker: RelayDeviceChecker {
    /// device key → its account key when its certificate is valid.
    var certs: [String: String] = [:]
    /// bundle ids that are valid.
    var bundles: Set<String> = []
    func certifiedAccountKey(certificate: NetJSON, devicePublicKey: String, now: Millis) -> String? {
        guard let apk = certs[devicePublicKey], certificate.str("apk") == apk, certificate.int("exp") > now else { return nil }
        return apk
    }
    func bundleValid(_ bundle: NetJSON, devicePublicKey: String, now: Millis) -> Bool { bundles.contains(bundle.str("id")) && bundle.int("exp") > now }
}

/// A fixed clock.
final class TestClock: @unchecked Sendable {
    private let t: Mutex<Millis>
    init(_ start: Millis) { t = Mutex(start) }
    var now: Millis { t.withLock { $0 } }
    func advance(_ ms: Millis) { t.withLock { $0 += ms } }
    var clock: NetClock { NetClock { [self] in self.now } }
}
