// Generated by the M5cet visual builder from flow.m5flow.json.
// Edit the flow in Functions → Builder (changes here are replaced on the next save),
// or use “Eject to code” there to keep working on this file by hand.

const __str = (v) => (v === undefined || v === null ? "" : typeof v === "string" ? v : typeof v === "object" && !(v instanceof Uint8Array) ? JSON.stringify(v, null, 2) : String(v));
const __clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined && v !== null && v !== ""));

export async function execute(inputs = {}) {
  let __result = null;
  // n1 · Read a card
  const n_n1 = await m5.nfc.read(__clean({ what: "uid", reader: "", tech: "", timeout: 20, secretRef: __str(undefined) || undefined }));
  // n4 · Template
  const n_n4 = "**Card** — UID `" + __str(n_n1?.card?.uid) + "` (" + __str(n_n1?.status) + ")";
  // n2 · Result
  const n_n2 = (__result = n_n1);
  // n5 · Send Markdown
  const n_n5 = await m5.caller.send(m5.out.markdown(__str(n_n4)));
  return __result;
}

