// DEBUG only: the console's sample state of every screen (server/android/design.ts
// SCREENS[].sample — what the console's preview binds; the same data
// ios/M5Kit/Tests/M5DesignTests resolves all screens with). Generated from
// ios/M5Kit/Tests/M5DesignTests/fixtures/catalog.json, one screen per line:
//
//   python3 -c "import json;d=json.load(open('ios/M5Kit/Tests/M5DesignTests/fixtures/catalog.json'));\
//     print(json.dumps({s['id']:s['sample'] for s in d['screens']},ensure_ascii=False,sort_keys=True))"
//
// RendererSampleTests fails when it is out of step with the fixture.

#if DEBUG
enum SampleScreenData {
    /// The screens of the catalogue, in its order.
    static let screens: [String] = [
        "splash",
        "lock",
        "enroll",
        "rooms",
        "rooms.item",
        "join",
        "room",
        "message.in",
        "message.out",
        "message.sys",
        "users",
        "users.item",
        "users.handle",
        "settings",
        "call",
        "update",
        "about",
        "flash",
        "tools",
        "attach",
        "send.options",
        "dictate.options",
        "call.options",
        "settings.user",
        "settings.messages",
        "settings.voice",
        "settings.location",
        "settings.calls",
        "settings.appearance",
        "settings.security",
        "ai",
        "voice",
        "nfc",
        "users.person",
        "settings.people",
        "nfc.builder",
        "settings.notify",
        "settings.voiceFx",
        "room.edit",
        "settings.profile",
        "log",
        "message.sender",
        "message.forward",
        "message.model",
    ]

    /// screen id → its sample variables (JSON).
    static let json = ##"""
{
"about":{"app":{"bundle":"6.0.0-b1","code":600,"name":"M5cet","version":"6.0.0"},"device":{"id":"and_…","model":"Pixel 9"},"server":{"fingerprint":"1A2B 3C4D …","kid":"AbCdEf0123456789","url":"https://chat.example.com"}},
"ai":{"ai":{"busy":false,"model":"anthropic/claude-sonnet-5-5","state":"ready"}},
"attach":{"composer":{"hasText":true,"private":false,"sealed":false,"tap":false,"vanish":0},"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}}},
"call":{"call":{"active":true,"duration":83,"mode":"audio","muted":false,"peers":2},"room":{"active":true,"connected":true,"key":"team","name":"team","selected":true,"status":"joined","unread":0,"users":4}},
"call.options":{"call":{"active":false},"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}}},
"dictate.options":{"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}},"voices":[{"label":"Default","value":""},{"label":"cs-CZ · jfs ★","value":"cs-cz-x-jfs-local"}]},
"enroll":{"app":{"bundle":"6.0.0-b1","code":600,"name":"M5cet","version":"6.0.0"},"enroll":{"error":"","server":"https://chat.example.com"}},
"flash":{"flash":{"level":"success","text":"Saved.","title":""}},
"join":{"error":"","form":{"name":"","passphrase":"","room":""}},
"lock":{"app":{"bundle":"6.0.0-b1","code":600,"name":"M5cet","version":"6.0.0"},"lock":{"attempts":1,"biometricAvailable":true,"error":"","left":7,"mode":"pin","wait":0}},
"log":{"form":{"logFilter":"all","logQuery":""},"log":{"count":4,"empty":false,"history":true,"items":[{"callable":true,"color":"@danger","day":"Dnes","detail":"Zmeškaný · Alice","dir":"missed","icon":"phone-off","id":"c:k3f9","newDay":true,"people":"Alice","room":"Tým","time":1760900000000,"type":"call","video":false},{"callable":false,"color":"@muted","day":"Dnes","detail":"Alice: Zavoláme se po obědě?","dir":"in","icon":"message-circle","id":"m:1a2b:m-77","newDay":false,"people":"Alice","room":"Tým","time":1760899000000,"type":"msg","video":false},{"callable":true,"color":"@primary","day":"Včera","detail":"Odchozí · video · 12:04 · Bob, Eva","dir":"out","icon":"video","id":"c:k3f2","newDay":true,"people":"Bob, Eva","room":"Rodina","time":1760810000000,"type":"call","video":true},{"callable":false,"color":"@muted","day":"Včera","detail":"Eva: Zapečetěná zpráva","dir":"in","icon":"message-square-lock","id":"m:9c8d:m-12","newDay":false,"people":"Eva","room":"Rodina","time":1760800000000,"type":"msg","video":false}],"loading":false,"more":false,"shown":4},"settings":{"callLog":false,"calls":{"history":true,"logName":"app"}}},
"message.forward":{"form":{"forward":{"canBack":true,"hasPeople":true,"icon":"","people":[{"id":"peer-1","name":"Bob"},{"id":"peer-2","name":"Eva"}],"room":"team","rooms":[{"here":true,"key":"team","name":"team","users":4},{"here":false,"key":"family","name":"family","users":3}],"sender":"Alice","step":"who","text":"Ahoj, jak to jde?","wholeRoom":false}}},
"message.in":{"msg":{"attachment":null,"changed":false,"id":"m1","mine":false,"replyTo":null,"sender":"Alice","text":"Ahoj, jak to jde?","time":1760000000000,"verified":true}},
"message.model":{"form":{"model":{"color":"#7bb234","emoji":false,"glyph":"phone","guide":"/hlr +420777123456\n/hlr +420777123456 long","hasInputs":true,"icon":"phone","inputs":[{"expect":"telefonní číslo v mezinárodním tvaru (+420…)","help":"Například +420 777 123 456","label":"Číslo","name":"number","required":true},{"expect":"jedna z: short, long","help":"","label":"","name":"format","required":false}],"keyword":"hlr","known":true,"line":"/hlr · přes Alice","local":false,"name":"Číslo a síť","senderId":"peer-1","summary":"Ověří telefonní číslo: země, operátor, dosažitelnost.","usage":"/hlr <number> [format]","visibility":"room","write":"/hlr "}}},
"message.out":{"msg":{"attachment":null,"id":"m2","mine":true,"replyTo":{"sender":"Alice","text":"Ahoj, jak to jde?"},"sender":"Mike","status":"sent","text":"Dobře, díky!","time":1760000060000}},
"message.sender":{"form":{"sender":{"canMessage":true,"function":false,"has":true,"id":"peer-9f2c41d0a7b3","me":false,"name":"Alice","nickDiffers":true,"photo":"","present":true,"profile":{"about":"Lezu a piju kávu.","avatar":"","cover":"","fields":[{"icon":"globe","label":"Blog","type":"url","value":"https://alice.example"}],"nickname":"Alice Nováková"},"title":"Alice Nováková","username":"bystry-sokol-7k3q"}}},
"message.sys":{"msg":{"id":"s1","text":"Alice joined","time":1760000000000}},
"nfc":{"nfc":{"available":true,"emulating":false,"enabled":true,"last":null,"state":"idle"},"room":{"name":"team"}},
"nfc.builder":{},
"room":{"call":{"active":false},"me":{"name":"Mike"},"room":{"active":true,"connected":true,"key":"team","name":"team","selected":true,"status":"joined","unread":0,"users":4},"rooms":[{"active":true,"connected":true,"key":"team","name":"team","selected":true,"status":"joined","unread":0,"users":4},{"active":false,"connected":true,"key":"family","name":"family","selected":true,"status":"joined","unread":7,"users":3}],"users":{"autoHide":false,"count":4,"dock":"right","open":true}},
"room.edit":{"form":{}},
"rooms":{"app":{"bundle":"6.0.0-b1","code":600,"name":"M5cet","version":"6.0.0"},"connectedCount":2,"rooms":[{"active":true,"connected":true,"key":"team","name":"team","selected":true,"status":"joined","unread":0,"users":4},{"active":false,"connected":true,"key":"family","name":"family","selected":true,"status":"joined","unread":7,"users":3},{"active":false,"connected":false,"key":"project-x","name":"project-x","selected":false,"status":"saved","unread":0,"users":0}],"selectedCount":2,"unreadTotal":7},
"rooms.item":{"room":{"active":false,"connected":true,"key":"family","name":"family","selected":true,"status":"joined","unread":7,"users":3}},
"send.options":{"composer":{"asVoice":false,"count":2,"hasText":true,"private":false,"sealCode":"","sealed":true,"tap":false,"vanish":60,"voiceText":false},"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}}},
"settings":{"app":{"bundle":"6.0.0-b1","code":600,"name":"M5cet","version":"6.0.0"},"settings":{}},
"settings.appearance":{"presets":[{"bg":"#f5f6f8","family":"design","fg":"#1c2330","label":"M5cet","onPrimary":"#ffffff","primary":"#e11d48","selected":true,"surface":"#ffffff","tone":"both","value":"design","variants":[{"color":"#e11d48","label":"Barva šablony","on":"#ffffff","selected":true,"value":""},{"color":"#c41c2c","label":"Červená","on":"#ffffff","selected":false,"value":"red"},{"color":"#b24a09","label":"Oranžová","on":"#ffffff","selected":false,"value":"orange"},{"color":"#1b7a48","label":"Zelená","on":"#ffffff","selected":false,"value":"green"},{"color":"#1560c9","label":"Modrá","on":"#ffffff","selected":false,"value":"blue"},{"color":"#7045e0","label":"Fialová","on":"#ffffff","selected":false,"value":"violet"},{"color":"#127a70","label":"Tyrkysová","on":"#ffffff","selected":false,"value":"teal"},{"color":"#c0195b","label":"Růžová","on":"#ffffff","selected":false,"value":"pink"}]},{"bg":"#f2f2f7","family":"system","fg":"#000000","label":"iOS 27","onPrimary":"#ffffff","primary":"#007bff","selected":false,"surface":"#ffffff","tone":"both","value":"ios","variants":[]},{"bg":"#0b0d19","family":"classic","fg":"#e4e8f7","label":"Midnight","onPrimary":"#ffffff","primary":"#8266f5","selected":false,"surface":"#111322","tone":"dark","value":"midnight","variants":[]},{"bg":"#f8f6f1","family":"classic","fg":"#2c231b","label":"Paper","onPrimary":"#ffffff","primary":"#b84c1e","selected":false,"surface":"#fdfdfb","tone":"light","value":"paper","variants":[]}],"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}}},
"settings.calls":{"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}}},
"settings.location":{"location":{"allowed":true,"permitted":true,"tracking":false},"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}}},
"settings.messages":{"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}}},
"settings.notify":{"account":{"signedIn":true,"username":"bystry-sokol-7k3q"},"notify":{"busy":false,"channels":[{"first":true,"id":"android","label":"Android app","last":false,"n":1,"used":true},{"first":false,"id":"webpush","label":"Browser (web push)","last":true,"n":2,"used":true},{"first":true,"id":"email","label":"E-mail","last":true,"n":0,"used":false}],"hours":[{"label":"00:00","value":"00:00"},{"label":"00:30","value":"00:30"},{"label":"01:00","value":"01:00"},{"label":"01:30","value":"01:30"},{"label":"02:00","value":"02:00"},{"label":"02:30","value":"02:30"},{"label":"03:00","value":"03:00"},{"label":"03:30","value":"03:30"},{"label":"04:00","value":"04:00"},{"label":"04:30","value":"04:30"},{"label":"05:00","value":"05:00"},{"label":"05:30","value":"05:30"},{"label":"06:00","value":"06:00"},{"label":"06:30","value":"06:30"},{"label":"07:00","value":"07:00"},{"label":"07:30","value":"07:30"},{"label":"08:00","value":"08:00"},{"label":"08:30","value":"08:30"},{"label":"09:00","value":"09:00"},{"label":"09:30","value":"09:30"},{"label":"10:00","value":"10:00"},{"label":"10:30","value":"10:30"},{"label":"11:00","value":"11:00"},{"label":"11:30","value":"11:30"},{"label":"12:00","value":"12:00"},{"label":"12:30","value":"12:30"},{"label":"13:00","value":"13:00"},{"label":"13:30","value":"13:30"},{"label":"14:00","value":"14:00"},{"label":"14:30","value":"14:30"},{"label":"15:00","value":"15:00"},{"label":"15:30","value":"15:30"},{"label":"16:00","value":"16:00"},{"label":"16:30","value":"16:30"},{"label":"17:00","value":"17:00"},{"label":"17:30","value":"17:30"},{"label":"18:00","value":"18:00"},{"label":"18:30","value":"18:30"},{"label":"19:00","value":"19:00"},{"label":"19:30","value":"19:30"},{"label":"20:00","value":"20:00"},{"label":"20:30","value":"20:30"},{"label":"21:00","value":"21:00"},{"label":"21:30","value":"21:30"},{"label":"22:00","value":"22:00"},{"label":"22:30","value":"22:30"},{"label":"23:00","value":"23:00"},{"label":"23:30","value":"23:30"}],"linked":true,"push":true,"serverOff":false,"signedIn":true,"status":""},"settings":{"notify":{"away":true,"call":true,"function":false,"mention":true,"message":true,"on":true,"order":"android,webpush","privacy":"sender","quiet":true,"quietFrom":"22:00","quietTo":"07:00","summon":true}}},
"settings.people":{"settings":{"people":{"contacts":true}}},
"settings.profile":{"account":{"signedIn":true,"username":"bystry-sokol-7k3q"},"form":{"pfAbout":"Lezu a piju kávu.","pfAboutAud":"room","pfAvatarAud":"room","pfCoverAud":"me","pfNick":"Alice","pfNickAud":"public","pfPreview":"room"},"profile":{"avatar":"","busy":false,"canAdd":true,"cover":"","dirty":true,"error":"","fields":[{"audIcon":"lock","audience":"me","icon":"phone","index":0,"invalid":false,"label":"Mobil","type":"phone","typeLabel":"Telefon","value":"+420 777 123 456"},{"audIcon":"globe","audience":"public","icon":"globe","index":1,"invalid":false,"label":"Blog","type":"url","typeLabel":"Web","value":"https://alice.example"}],"hasAvatar":false,"hasCover":false,"initials":"A","loading":false,"msg":"","preview":{"about":"Lezu a piju kávu.","avatar":"","cover":"","empty":false,"fields":[{"icon":"globe","label":"Blog","value":"https://alice.example"}],"nickname":"Alice"},"ready":true,"signedIn":true}},
"settings.security":{"security":{"biometric":true,"biometricAvailable":true,"maxAttempts":8,"pinLength":6,"screenshots":false,"wipe":true},"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}}},
"settings.user":{"account":{"credential":"Xy12AbCdEf34…","groups":"user, staff","keyVerified":true,"lastLogin":1760900000000,"passkeys":2,"sessions":3,"signedIn":true,"since":1760000000000,"username":"bystry-sokol-7k3q"},"connection":{"checkin":1760900000000,"crypto":"v3","protocol":2,"push":"fcm","rooms":2,"server":"https://chat.example.com","status":"joined","turn":2},"keys":{"device":"and_mun44x0d02651c81e33d","deviceKey":"ptM0vNPIIsAo4sr7","identity":"3C4D 5E6F 7A8B 9C0D","server":"A6D3 34BC D3C8 22C0"}},
"settings.voice":{"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}},"voices":[{"label":"Default","value":""},{"label":"cs-CZ · jfs ★","value":"cs-cz-x-jfs-local"}]},
"settings.voiceFx":{"settings":{"voiceFx":{"echo":0,"echoMs":250,"formant":-3,"gain":0,"on":true,"pitch":-5,"preset":"custom","robot":0,"whisper":0}},"voiceFx":{"active":true,"allowed":true,"testing":"idle"}},
"splash":{"app":{"bundle":"6.0.0-b1","code":600,"name":"M5cet","version":"6.0.0"},"busy":true,"status":"Decrypting…"},
"tools":{"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}},"tools":{"ai":true,"nfc":true,"voice":true}},
"update":{"update":{"kind":"bundle","notes":"New look of the rooms.","progress":0.4,"size":182000,"state":"downloading","version":"6.0.0-b2"}},
"users":{"autoHide":false,"count":2,"dock":"right","users":[{"away":false,"me":false,"name":"Alice","verified":true},{"away":false,"me":true,"name":"Mike","verified":true}]},
"users.handle":{"count":4,"edge":"right","open":false},
"users.item":{"user":{"away":false,"me":false,"name":"Alice","verified":true}},
"users.person":{"form":{"person":{"app":"","avatarBg":"#38ae2929","avatarFg":"#ffb62020","away":false,"canLink":true,"candidates":"host → srflx · UDP","changed":false,"channel":"open","codec":"opus","contact":"Alice Nováková","contactsOn":true,"dtls":"sha-256 3A:5F:…","fingerprint":"8537 3E64 524D FF04 7F54 2310 0FA3 B932","glyph":"A","hasSafety":true,"id":"peer-9f2c41d0a7b3","linked":true,"me":false,"name":"Alice","others":2,"peerShort":"peer-9f2c41d0a7b3","photo":"","remote":"203.0.113.7:51234","room":"team","rtt":38,"rttText":"38 ms","safety":"13286 60170 84613 24995\n23962 36648 18264 48418\n04707 59157 69365 29038","safetyVerified":false,"security":"AES-GCM 256 (E2EE) · DTLS 1.2","selectable":true,"selected":false,"signal":4,"signalColor":"@success","signalIcon":"signal","signedIn":true,"sinceText":"12 min 5 s","status":"online","statusColor":"@success","statusIcon":"circle-check","statusLabel":"Online","traffic":"84.2 kB / 91.6 kB","transport":"direct","transportLabel":"Direct (P2P)","username":"bystry-sokol-7k3q","verified":true}},"settings":{"people":{"contacts":true}}},
"voice":{"settings":{"appearance":{"accent":"","bubbles":"rounded","density":"normal","fontScale":1,"preset":"design","tone":"system"},"callLog":false,"calls":{"audioText":false,"speaker":true},"location":{"inHeader":false,"interval":60,"precise":true,"track":false},"look":{"buttons":"filled","font":"","haptics":true,"hintSendOptions":false,"motion":"normal","press":"ripple","shape":"pill","speed":1,"toolsDock":true,"v":1,"variant":""},"messages":{"enterSends":false,"readReceipts":true,"receipts":true,"ttlMinutes":0,"vanishSeconds":60},"nfc":{"emulate":false},"security":{"shufflePin":false},"voice":{"autoplay":false,"dictateSend":false,"dictateSpeak":false,"engine":"device","lang":"","pitch":1,"rate":1,"voice":""}},"voice":{"available":true,"dictating":false,"listening":false,"speaking":false},"voices":[{"label":"Default","value":""},{"label":"cs-CZ · jfs ★","value":"cs-cz-x-jfs-local"}]}
}
"""##
}
#endif
