// Generated by the M5cet visual builder from flow.m5flow.json.
// Edit the flow in Functions → Builder (changes here are replaced on the next save),
// or use “Eject to code” there to keep working on this file by hand.

const __str = (v) => (v === undefined || v === null ? "" : typeof v === "string" ? v : typeof v === "object" && !(v instanceof Uint8Array) ? JSON.stringify(v, null, 2) : String(v));
const __get = (o, path) => String(path).split(".").filter(Boolean).reduce((a, k) => (a === undefined || a === null ? undefined : a[k]), o);
const __clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined && v !== null && v !== ""));

export async function execute(inputs = {}) {
  // n1 · Form
  const n_n1 = await m5.caller.send(m5.out.form({"name":"tel-call","title":"Phone call","text":"Call a phone number and say something (ring timeout 10 s)","submit":"Send","labels":"top","fields":[{"name":"to","type":"tel","label":"Number to call","required":true,"pattern":"^\\+[1-9][0-9]{6,14}$","placeholder":"+420603123456","help":"In the international form: +420603123456"},{"name":"text","type":"textarea","label":"What to say","required":true,"rows":3,"placeholder":"Dobrý den, …"},{"name":"timeout","type":"number","label":"Ring for (seconds)","min":5,"max":60,"step":1,"default":10},{"name":"from","type":"tel","label":"From (empty: the provider's number)","pattern":"(^\\+[1-9][0-9]{6,14}$)?"}]}));
  return null;
}

export async function form(inputs = {}) {
  // n2 · Entry point data
  const n_n2 = inputs;
  // n5 · Get field
  const n_n5 = __get(n_n2.values, "to");
  // n8 · Get field
  const n_n8 = __get(n_n2.values, "text");
  // n3 · Phone call
  const n_n3 = await m5.telephony.call({ ...__clean(n_n2.values || {}), ...__clean({ to: __str(n_n5), say: __str(n_n8), from: "", timeout: 10, provider: "", wait: true, on: __clean({ answer: "", hangup: "", busy: "", noanswer: "", failed: "" }) }) });
  // n13 · Get field
  const n_n13 = __get(n_n2.values, "to");
  // n15 · Get field
  const n_n15 = __get(n_n3, "status");
  // n17 · Get field
  const n_n17 = __get(n_n3, "durationSec");
  // n11 · Template
  const n_n11 = "**Call to " + __str(n_n13) + "** — " + __str(n_n15) + ", " + __str(n_n17) + " s";
  // n12 · Send Markdown
  const n_n12 = await m5.caller.send(m5.out.markdown(__str(n_n11)));
  return null;
}

export async function error(inputs = {}) {
  // n23 · Entry point data
  const n_n23 = inputs;
  // n24 · Get field
  const n_n24 = __get(n_n23.error, "message");
  // n25 · Flash
  const n_n25 = await m5.caller.flash(__str(n_n24), "error");
  return null;
}

