// Generated by the M5cet visual builder from flow.m5flow.json.
// Edit the flow in Functions → Builder (changes here are replaced on the next save),
// or use “Eject to code” there to keep working on this file by hand.

const __str = (v) => (v === undefined || v === null ? "" : typeof v === "string" ? v : typeof v === "object" && !(v instanceof Uint8Array) ? JSON.stringify(v, null, 2) : String(v));
const __get = (o, path) => String(path).split(".").filter(Boolean).reduce((a, k) => (a === undefined || a === null ? undefined : a[k]), o);
const __clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined && v !== null && v !== ""));

export async function execute(inputs = {}) {
  let __result = null;
  // n1 · EMV: read everything
  const n_n1 = await m5.nfc.emv.report(__clean({ format: "html", send: true, history: true, deep: true, fullPan: false, maxApps: 8, reader: "", timeout: 45 }));
  // n2 · Result
  const n_n2 = (__result = n_n1?.summary);
  return __result;
}

export async function error(inputs = {}) {
  // n4 · Entry point data
  const n_n4 = inputs;
  // n5 · Get field
  const n_n5 = __get(n_n4.error, "message");
  // n6 · Flash
  const n_n6 = await m5.caller.flash(__str(n_n5), "error");
  return null;
}

