// Generated by the M5cet visual builder from flow.m5flow.json.
// Edit the flow in Functions → Builder (changes here are replaced on the next save),
// or use “Eject to code” there to keep working on this file by hand.

const __clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined && v !== null && v !== ""));

export async function execute(inputs = {}) {
  let __result = null;
  // n1 · Scan a card
  const n_n1 = await m5.nfc.scan(__clean({ reader: "", tech: "", timeout: 30 }));
  // n4 · Send JSON
  const n_n4 = await m5.caller.send(m5.out.json(n_n1, { title: "Card" }));
  // n2 · Result
  const n_n2 = (__result = n_n1);
  return __result;
}

