// Generated by the M5cet visual builder from flow.m5flow.json.
// Edit the flow in Functions → Builder (changes here are replaced on the next save),
// or use “Eject to code” there to keep working on this file by hand.

const __str = (v) => (v === undefined || v === null ? "" : typeof v === "string" ? v : typeof v === "object" && !(v instanceof Uint8Array) ? JSON.stringify(v, null, 2) : String(v));
const __get = (o, path) => String(path).split(".").filter(Boolean).reduce((a, k) => (a === undefined || a === null ? undefined : a[k]), o);
const __clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined && v !== null && v !== ""));

export async function execute(inputs = {}) {
  // n1 · Form
  const n_n1 = await m5.caller.send(m5.out.form({"name":"tel-messenger","title":"Messenger","text":"Send a Facebook Messenger message","submit":"Send","labels":"top","fields":[{"name":"to","type":"text","label":"Recipient (page-scoped id)","required":true,"pattern":"^[0-9]{5,32}$"},{"name":"text","type":"textarea","label":"Text","required":true,"rows":3},{"name":"tag","type":"select","label":"Outside 24 hours","default":"","options":[{"value":"","label":"—"},{"value":"HUMAN_AGENT","label":"HUMAN_AGENT"}]}]}));
  return null;
}

export async function form(inputs = {}) {
  // n2 · Entry point data
  const n_n2 = inputs;
  // n5 · Get field
  const n_n5 = __get(n_n2.values, "to");
  // n8 · Get field
  const n_n8 = __get(n_n2.values, "text");
  // n3 · WhatsApp / Viber / Messenger
  const n_n3 = await m5.telephony.messenger({ ...__clean(n_n2.values || {}), ...__clean({ to: __str(n_n5), text: __str(n_n8), from: "", provider: "" }) });
  // n13 · Get field
  const n_n13 = __get(n_n2.values, "to");
  // n15 · Get field
  const n_n15 = __get(n_n3, "status");
  // n11 · Template
  const n_n11 = "**Messenger to " + __str(n_n13) + "** — " + __str(n_n15);
  // n12 · Send Markdown
  const n_n12 = await m5.caller.send(m5.out.markdown(__str(n_n11)));
  return null;
}

export async function error(inputs = {}) {
  // n20 · Entry point data
  const n_n20 = inputs;
  // n21 · Get field
  const n_n21 = __get(n_n20.error, "message");
  // n22 · Flash
  const n_n22 = await m5.caller.flash(__str(n_n21), "error");
  return null;
}

