// Generated by the M5cet visual builder from flow.m5flow.json.
// Edit the flow in Functions → Builder (changes here are replaced on the next save),
// or use “Eject to code” there to keep working on this file by hand.

const __str = (v) => (v === undefined || v === null ? "" : typeof v === "string" ? v : typeof v === "object" && !(v instanceof Uint8Array) ? JSON.stringify(v, null, 2) : String(v));
const __clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined && v !== null && v !== ""));

export async function execute(inputs = {}) {
  let __result = null;
  // n1 · M5Cet: open records
  const n_n1 = await m5.nfc.m5.read(__clean({ reader: "", timeout: 30, secretRef: __str(undefined) || undefined }));
  // n4 · Send JSON
  const n_n4 = await m5.caller.send(m5.out.json(n_n1, { title: "M5Cet records" }));
  // n2 · Result
  const n_n2 = (__result = n_n1);
  return __result;
}

