// Generated by the M5cet visual builder from flow.m5flow.json.
// Edit the flow in Functions → Builder (changes here are replaced on the next save),
// or use “Eject to code” there to keep working on this file by hand.

const __str = (v) => (v === undefined || v === null ? "" : typeof v === "string" ? v : typeof v === "object" && !(v instanceof Uint8Array) ? JSON.stringify(v, null, 2) : String(v));
const __get = (o, path) => String(path).split(".").filter(Boolean).reduce((a, k) => (a === undefined || a === null ? undefined : a[k]), o);
const __clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined && v !== null && v !== ""));

export async function execute(inputs = {}) {
  // n1 · Form
  const n_n1 = await m5.caller.send(m5.out.form({"name":"tel-did","title":"Phone bridge","text":"Lend a phone number and a 5-digit code that connect a caller to a room member","submit":"Send","labels":"top","fields":[{"name":"room","type":"text","label":"Room (its id or hash)","required":true},{"name":"member","type":"text","label":"Member (name or peer id)","required":true},{"name":"minutes","type":"number","label":"Valid for (minutes)","min":1,"max":120,"default":10},{"name":"mode","type":"select","label":"Mode","default":"auto","options":[{"value":"auto","label":"audio when taken, else text"},{"value":"audio","label":"audio"},{"value":"text","label":"speech ↔ text"}]}]}));
  return null;
}

export async function form(inputs = {}) {
  // n2 · Entry point data
  const n_n2 = inputs;
  // n5 · Get field
  const n_n5 = __get(n_n2.values, "room");
  // n8 · Get field
  const n_n8 = __get(n_n2.values, "member");
  // n3 · Temporary number
  const n_n3 = await m5.telephony.did.allocate({ ...__clean(n_n2.values || {}), ...__clean({ room: ((r) => (r && typeof r === "object" ? r.id : r))(n_n5), member: __str(n_n8), minutes: 10, mode: "auto", language: "cs", number: "" }) });
  // n13 · Get field
  const n_n13 = __get(n_n3, "number");
  // n15 · Get field
  const n_n15 = __get(n_n3, "code");
  // n17 · Get field
  const n_n17 = __get(n_n3, "expiresAt");
  // n11 · Template
  const n_n11 = "**Call " + __str(n_n13) + "** and type **" + __str(n_n15) + "#** — valid until " + __str(n_n17);
  // n12 · Send Markdown
  const n_n12 = await m5.caller.send(m5.out.markdown(__str(n_n11)));
  return null;
}

export async function error(inputs = {}) {
  // n23 · Entry point data
  const n_n23 = inputs;
  // n24 · Get field
  const n_n24 = __get(n_n23.error, "message");
  // n25 · Flash
  const n_n25 = await m5.caller.flash(__str(n_n24), "error");
  return null;
}

