// Generated by the M5cet visual builder from flow.m5flow.json.
// Edit the flow in Functions → Builder (changes here are replaced on the next save),
// or use “Eject to code” there to keep working on this file by hand.

const __str = (v) => (v === undefined || v === null ? "" : typeof v === "string" ? v : typeof v === "object" && !(v instanceof Uint8Array) ? JSON.stringify(v, null, 2) : String(v));
const __get = (o, path) => String(path).split(".").filter(Boolean).reduce((a, k) => (a === undefined || a === null ? undefined : a[k]), o);
const __clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined && v !== null && v !== ""));

export async function execute(inputs = {}) {
  // n1 · Form
  const n_n1 = await m5.caller.send(m5.out.form({"name":"tel-lookup","title":"Number lookup","text":"Everything about a phone number: country, type, carrier, name, porting, roaming","submit":"Send","labels":"top","fields":[{"name":"number","type":"tel","label":"Number","required":true,"pattern":"^[+0-9 ()./-]{3,24}$","placeholder":"+420603123456"},{"name":"country","type":"text","label":"Country for a national number (ISO)","pattern":"^([A-Za-z]{2})?$","placeholder":"CZ"},{"name":"offline","type":"switch","label":"Only what is free (no providers)"}]}));
  return null;
}

export async function form(inputs = {}) {
  // n2 · Entry point data
  const n_n2 = inputs;
  // n5 · Get field
  const n_n5 = __get(n_n2.values, "number");
  // n3 · Number lookup
  const n_n3 = await m5.telephony.lookup(__str(n_n5), { ...__clean(n_n2.values || {}), ...__clean({ offline: undefined, fields: undefined, country: "" }) });
  // n8 · Send JSON
  const n_n8 = await m5.caller.send(m5.out.json(n_n3, { title: "Number" }));
  return null;
}

export async function error(inputs = {}) {
  // n10 · Entry point data
  const n_n10 = inputs;
  // n11 · Get field
  const n_n11 = __get(n_n10.error, "message");
  // n12 · Flash
  const n_n12 = await m5.caller.flash(__str(n_n11), "error");
  return null;
}

