// Generated by the M5cet visual builder from flow.m5flow.json.
// Edit the flow in Functions → Builder (changes here are replaced on the next save),
// or use “Eject to code” there to keep working on this file by hand.

const __str = (v) => (v === undefined || v === null ? "" : typeof v === "string" ? v : typeof v === "object" && !(v instanceof Uint8Array) ? JSON.stringify(v, null, 2) : String(v));
const __get = (o, path) => String(path).split(".").filter(Boolean).reduce((a, k) => (a === undefined || a === null ? undefined : a[k]), o);
const __table = (rows, cols) => { const list = Array.isArray(rows) ? rows : rows === undefined || rows === null ? [] : [rows]; const columns = cols && cols.length ? cols : list.length && !Array.isArray(list[0]) && typeof list[0] === "object" && list[0] !== null ? [...new Set(list.flatMap((r) => Object.keys(r || {})))] : ["value"]; return [columns, list.map((r) => (Array.isArray(r) ? r : r !== null && typeof r === "object" ? columns.map((c) => r[c]) : [r]))]; };
const __clean = (o) => Object.fromEntries(Object.entries(o).filter(([, v]) => v !== undefined && v !== null && v !== ""));

export async function execute(inputs = {}) {
  let __result = null;
  // n1 · EMV: read everything
  const n_n1 = await m5.nfc.emv.report(__clean({ format: "object", send: false, history: true, deep: false, fullPan: false, maxApps: 8, reader: "", timeout: 45 }));
  // n2 · If
  const n_n2 = n_n1?.data;
  const n_n2_c = Boolean(n_n1?.ok);
  // n7 · Result
  const n_n7 = (__result = n_n1?.summary);
  // n3 · EMV: transaction history
  let n_n3;
  if (n_n2_c) {
    n_n3 = m5.nfc.emv.history(n_n2);
  }
  // n5 · Get field
  let n_n5;
  if (!n_n2_c) {
    n_n5 = __get(n_n2, "message");
  }
  // n4 · Send table
  let n_n4;
  if (n_n2_c) {
    n_n4 = await m5.caller.send(m5.out.table(...__table(n_n3, ["date","time","amount","currency","merchant","type","country","atc"]), { title: "Transaction history" }));
  }
  // n6 · Flash
  let n_n6;
  if (!n_n2_c) {
    n_n6 = await m5.caller.flash(__str(n_n5), "warning");
  }
  return __result;
}

export async function error(inputs = {}) {
  // n15 · Entry point data
  const n_n15 = inputs;
  // n16 · Get field
  const n_n16 = __get(n_n15.error, "message");
  // n17 · Flash
  const n_n17 = await m5.caller.flash(__str(n_n16), "error");
  return null;
}

